import { StyleSheet } from "react-native";

const todoStyle = StyleSheet.create({
  
  main: {
    display: "flex",
    top: 0,
    position: "absolute",
    width: "100%",
    alignItems: "center",
    justifyContent: "start",
    marginTop: 45,
    // marginTop: 30,
  },
  todo: {
    width: "100%",
    display: "flex",
    padding: 12,
    top: {
      width: "100%",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginHorizontal: 5,
    },
    mid: {
      paddingTop: 15,
      marginHorizontal: 5,
      icon: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 2,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        width: 50,
        height: 50,
        borderRadius: 5,
      },
    },
  },
  todomain: {
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "start",
    padding: 12,
    borderRadius: 10,
  },
  t_scroll: {
    container: {
      paddingVertical: 10,
    },
    scrollViewContainer: {
      height: 500, // Adjust the height as needed
      // backgroundColor: "rgba(255, 255, 255, 0.2)",
      paddingHorizontal: 6,
    },
    scrollViewContent: {
      flexGrow: 1,
      justifyContent: "start",
    },
    item: {
      backgroundColor: "#ffffff33",
      paddingRight: 5,
      marginBottom: 8,
      borderRadius: 5,
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    itemText: {
      fontSize: 16,
      color: "#fff",
      fontWeight: "semi-bold",
      paddingVertical: 5,
    },
    itemLeft: {
      display: "flex",
      alignItems: "center",
      flexDirection: "row",
      height: "100%",
      gap: 5,
    },
  },
  popup: {
    NewcloseButton: {
      marginTop: 10,
      width: 60,
      padding: 3,
      borderRadius: 5,
      backgroundColor: "gray", // change
    },
    popupContainer: {
      flex: 1,
      paddingTop: 20,
      justifyContent: "start",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    popupContent: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "white",
      width: 370,
      padding: 10,
      borderRadius: 5,
      marginTop: 45,
    },
    popupText: {
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 10,
    },
    closeButton: {
      marginTop: 10,
    },
    closeButtonText: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 5,
      color: "#dc3545",
      fontWeight: 600,
      fontSize: 16,
      borderWidth: 2,
      borderColor: "#6c757d",
      paddingVertical: 7,
      paddingHorizontal: 5,
    },
    add: {
      width: 360,
      padding: 5,
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    input: {
      width: 295,
      padding: 10,
      borderRadius: 5,
      borderWidth: 2,
      borderColor: "#2196f3",
    },
    addBtn: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 4,
      color: "white",
      fontWeight: 600,
      fontSize: 15,
      backgroundColor: "#648feb",
      paddingVertical: 10,
      paddingHorizontal: 7,
    },
    catGroup: {
      display: "flex",
      flexColBetween: "row",
      alignItems: "center",
      justifyContent: "space-around",
    },
    catBtn: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 4,
      color: "white",
      fontWeight: 600,
      fontSize: 15,
      paddingVertical: 10,
      paddingHorizontal: 7,
      textTransform: "uppercase", 
    },
  },
});

export default todoStyle;
